### PR TITLE
LPS-88984 Add Youtube portlet iframe resizing when portlet is added to page, dragged to new column, or window is resized

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-88984 Add Youtube portlet iframe resizing when portlet is added to page, dragged to new column, or window is resized

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Hi @jrao, I talked to Angelo about this and he says you can send your pull requests to @ChrisKian instead.

**Comment by jrao** [comment]
Sounds good. Sent https://github.com/ChrisKian/liferay-portal/pull/101

**Pull request closed without merging**
