### PR TITLE
LPS-76955

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPP-28468
https://issues.liferay.com/browse/LPS-76955

We implement key modification in the JSONWS GUI so that the GUI can properly handle objects and nulls.  For an additional use case see LPS-74117.

Feel free to ask any questions.

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test

**Comment by gregory-bretall** [comment]
@SpencerWoo I'll try and look through and review this tomorrow.

**Comment by SpencerWoo** [comment]
@gregory-bretall sounds good.  Customer closed LESA with workaround so it's low priority (even though we're keeping the LPP open) so if it's on hold until Tuesday that's acceptable if necessary.

**Comment by lipusz** [comment]
Hi Guys,

Please make sure it goes through the Application Security team too.

Side notes:
- try to avoid using internal-only ticket identifiers such as LPP on public PRs.
- The **[TS]** designation should be present on TS reletad PRs.

Thanks for working on it!

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1547

**Pull request closed without merging**
