### PR TITLE
LPS-81901 set configuration scope

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-81901

I believe these are incorrectly scoped.  As this escalates in review I'm looking to hear from engineers on this and whether there are more system settings that are improperly scoped.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test

**Comment by SpencerWoo** [comment]
@gregory-bretall no rush but unsure if you're aware of this LPS.  The intention is this fix is pushed to engineers who can look and determine the validity of changing these configuration scopes

**Comment by SpencerWoo** [comment]
ci:reopen

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1641

Sorry for the huge delay here.

**Pull request closed without merging**
