### PR TITLE
[TS] LPS-82700 Browse icon isn't visible when using images to link

### PR DESCRIPTION
**Pull request by rolandpakai**
https://issues.liferay.com/browse/LPS-82700

Hi @gregory-bretall,

please check my fix regarding browse icon on image.

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @gregory-bretall, @rolandpakai, I've cherry-picked this and pushed it with other changes to brian at https://github.com/brianchandotcom/liferay-portal/pull/60777

**Comment by rolandpakai** [comment]
Great, thanks!

**Comment by gregory-bretall** [comment]
Since Chema has resent this already, I'll close this Pull out.

**Pull request closed without merging**
