### PR TITLE
LPS-89919 added a +1 to the set value of MaxTerm when folder facet is being built

### PR DESCRIPTION
**Pull request by knchau**
[https://issues.liferay.com/browse/LPS-89919](url)

### CODE REVIEW

**Comment by gregory-bretall** [comment]
ci:test:sf

**Comment by gregory-bretall** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Hi @knchau, I wasn't able to reproduce this on the latest master branch (I was testing on git hash 242da85d4a7e3411d2262f2239a4b243b53fec47 for master). Could you retest on the latest master without your fix and confirm that the bug is still reproducible? Just leave your results in a comment on this PR and I'll get back to it when I'm back on Monday.

**Comment by knchau** [comment]
I tested it on git hash [https://github.com/liferay/liferay-portal/commit/23ab0266e163b69bc904853b12b28595f485d2cb](23ab026) and it seems to be reproducible.

**Comment by gregory-bretall** [comment]
Closing this as I am still unable to reproduce the issue. Seems like it may be related to https://issues.liferay.com/browse/LPS-90187

**Pull request closed without merging**
