### PR TITLE
LPS-89294 NoConnectionException if live server is down when switching tabs in Publishing > Staging

### PR DESCRIPTION
**Pull request by knchau**
Incorporated suggested changes from previous pull [#482](https://github.com/moltam89/liferay-portal/pull/482) 

https://issues.liferay.com/browse/LPS-89294

Notes from previous pull: 

> The issue was that the log error was being thrown on the console. I swallowed the log error if it was a ConnectException and displayed a UI error instead. I had to throw a RemoteExportException to display the proper banner by validating if the remote server is still live. If the connection is severed, it would throw a RemoteExportException for each tab and add a session error. I had to add session error for resourceRequest and renderRequest because the processes tab's view.jsp is called multiple times. renderRequest being used for the first call and resourceRequest for the calls thereafter. Scheduled tab's view.jsp includes the error file because processes tab handles the error message in its liferay-staging tag. The UI between the banner displays are different between the tabs because the processes tab has a management toolbar that has a margin-bottom which provides the gap between the toolbar and the banner whereas the scheduled tab only has the navigation toolbar which does not have any margins so there is no gap between that toolbar and the banner. The banners do not have any particular unique traits to provide a quick fix, so this is determined to be a separate issue.

And additionally: 

> The fix was to throw an exception when switching between tabs, resulting in a UI display that there is no connection to the remote server. The error log is swallowed from the change to the service_http template.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Is there a reason that we're changing the taglib to add an x to the banner on this ticket? Seems a bit outside of the scope of the fix and might be better suited to being on its own ticket so it's more transparent that we're adding this functionality. Let me know what you think

**Comment by knchau** [comment]
I added the close functionality on this ticket because it was suggested on the previous pr, but I do agree that it would be better suited to have it be its own ticket. Would the creation of the ticket be after this fix is committed to master? Also, should I just remove the commit from this pr or should I send a new one?

**Comment by gregory-bretall** [comment]
Just remove the commit from this PR and send it in on a new LPS at the same time. As far as I can tell they're not at all dependent on each other

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1792

**Pull request closed without merging**
