### PR TITLE
LPS-88649 Get rid of the Liferay message for staging process

### PR DESCRIPTION
**Pull request by knchau**

### CODE REVIEW

**Comment by knchau** [comment]
https://issues.liferay.com/browse/LPS-88649

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
@knchau could you include a reference as to why this issue is being resent?

**Comment by knchau** [comment]
Tamas and the Staging Team wanted to change the expected behavior [ref](https://github.com/moltam89/liferay-portal/pull/466)

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1774

**Pull request closed without merging**
