### PR TITLE
LPS-82725

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-82725

Web content cannot be created in IE11 since `removeInstance` is using method definition which is not supported in IE11. This can be resolved by adding function. 

Let me know if there are any questions or comments.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, nice catch! I'm picking this and pushing it to Brian right away.

Thanks!

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60570

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
