### PR TITLE
LPS-86526

### PR DESCRIPTION
**Pull request by frankfu926**
https://issues.liferay.com/browse/LPS-86526

Added top and bottom padding for center aligned images in blogs! :smiley:

### CODE REVIEW

**Comment by frankfu926** [comment]
ci:test:relevant

**Comment by frankfu926** [comment]
ci:test:sf

**Comment by gregory-bretall** [comment]
Thank you for taking my suggestions in regards to adding the margin-left and margin-right checks to the selector. However, upon looking at it more I think that we should be grouping all of the selectors unique to center alignment (display: block and the margin-left/right: auto) so that it only applies the rule if all of these selectors are present on the element

**Comment by gregory-bretall** [comment]
In my testing this seemed fine. Resent to https://github.com/blzaugg/liferay-portal/pull/190

**Pull request closed without merging**
