### PR TITLE
LPS-78396 Update Users.Profile.Friendly.URL Description For Its Inten…

### PR DESCRIPTION
**Pull request by brianikim**
…ded Use

### CODE REVIEW

**Comment by brianikim** [comment]
Hello @gregory-bretall ,

https://issues.liferay.com/browse/LPS-78396

The current description of users.profile.friendly.url is not fully sufficient in helping customers understand the intended use of the portal property. 
An example of such misunderstanding can be seen in the LPP associated with the LPS.
Therefore, I have made changes to the descriptions of users.profile.friendly.url to clarify how this property should be used.
The change was made with help with a SME sub-task that can also be found in the LPS.

If you have any questions, please let me know. Thanks.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci:test

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1578

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1582
Apologies for not closing this sooner.

**Pull request closed without merging**
