### PR TITLE
LPS-89294 Logs are placed in an if block and does not enter if it is …

### PR DESCRIPTION
**Pull request by knchau**
…a ConnectException

### CODE REVIEW

**Comment by knchau** [comment]
https://issues.liferay.com/browse/LPS-89294

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
ci:test:sf

**Comment by gregory-bretall** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Closing as per our conversation. Try and implement an improved error on the frontend to match with similar other connection lost errors.

**Pull request closed without merging**
