### PR TITLE
LPS-91408 reload after modal close

### PR DESCRIPTION
**Pull request by ryannealeigh1**
https://issues.liferay.com/browse/LPS-91408

Resent from https://github.com/blzaugg/liferay-portal/pull/213

### CODE REVIEW

**Comment by ryannealeigh1** [comment]
ci:test:sf

**Comment by ryannealeigh1** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Make sure to not include links to private JIRA projects like LPP on PRs to public repos @ryannealeigh1, include a link to the LPS instead

**Comment by ryannealeigh1** [comment]
@gregory-bretall Sorry about that, it was an accident.

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonmak08/liferay-portal/pull/2062

**Pull request closed without merging**
