### PR TITLE
LPS-78521 Fix Accessibility for Select Button in User Profile Image S…

### PR DESCRIPTION
**Pull request by brianikim**
…creen

### CODE REVIEW

**Comment by brianikim** [comment]
https://issues.liferay.com/browse/LPS-78521

Hello @gregory-bretall,

The issue here is that the Select button for selecting a user's profile image does not adhere to accessibility standards.

The fix here is to:

1. Set tabindex to 0 so that the button can now be tabbed to.
2. Provide a simple javascript that checks on keypress whether the keypress was space or enter, then trigger .click(); this allows space and enter to be used to simulate a mouse click on the button.

As for the design implementation of the code itself, I followed

https://github.com/liferay/liferay-portal/blob/ee43b19c0cff85df998512ef644abe527961979f/modules/apps/forms-and-workflow/portal-workflow/portal-workflow-web/src/main/resources/META-INF/resources/definition/edit_workflow_definition.jsp#L336-L345

as a precedent.

If you have any questions, please let me know. Thanks.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci:test

**Comment by gregory-bretall** [comment]
Solution looks good @brianikim but could you override the branch with a commit message more specific to what your change is? I think it would be best to mention that you're allowing the Select button to specifically be keyboard accessible/accessible by tab and then clickable using space/enter. There's no need to resend the PR, just override your current branch with a different commit message

**Comment by brianikim** [comment]
@gregory-bretall ,

I updated the commit message as you requested. Thanks :D

**Comment by gregory-bretall** [comment]
Thanks @brianikim!

**Comment by gregory-bretall** [comment]
ci:retest

**Comment by gregory-bretall** [comment]
ci:stop

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1565

**Pull request closed without merging**
