### PR TITLE
LPS-92048 v7_0_5.UpgradeExpando takes a really long time to complete

### PR DESCRIPTION
**Pull request by knchau**
The issue is that database upgrades take a longer time to complete due to the use of the clause NOT IN, since it needs to look for the values twice. This degrades the query performance. NOT EXISTS looks at the missing values once, making this query ore efficient.

[LPP-33245](https://issues.liferay.com/browse/LPP-33245)
[LPS-92048](https://issues.liferay.com/browse/LPS-92048)

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @knchau @gregory-bretall 

Please see my comment here:
https://issues.liferay.com/browse/LPP-33245?focusedCommentId=1735725&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1735725

Thanks.

**Comment by gregory-bretall** [comment]
Closing based on Alberto's comment here https://issues.liferay.com/browse/LPP-33245?focusedCommentId=1735725&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1735725. Resend when you've adjusted the fix to his suggestion.

**Pull request closed without merging**
