### PR TITLE
LPS-85955 Fixed unescaped file and folder names in DL

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-85955

Resent from https://github.com/SpencerWoo/liferay-portal/pull/21
Details https://github.com/SpencerWoo/liferay-portal/pull/21#issue-220113696

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:reopen

**Comment by gregory-bretall** [comment]
Looks fine to me, resent to https://github.com/jonathanmccann/liferay-portal/pull/1707

**Pull request closed without merging**
