### PR TITLE
LPS-78794 Enable Activities Portlet to Provide Profile Links for User…

### PR DESCRIPTION
**Pull request by brianikim**
… Mentions

### CODE REVIEW

**Comment by brianikim** [comment]
https://issues.liferay.com/browse/LPS-78794

Hello @gregory-bretall ,

The issue here is that the activities portlet and the microblogs portlet have conflicting behaviors in regards to how user mentions are displayed. For microblogs portlet, the user mention is converted into a  href that allows users to click on the mentioned user's profile. For ex, in a microblogs portlet, if you write a comment saying "Hello @USER" @USER will be converted into the mentioned profile link. However, in the activities portlet, the same comment will be displayed as "Hello [@USER]".

The fix here is to use the already available function of replaceUserTags() found in 
https://github.com/liferay/liferay-portal/blob/e0ffae30b9ea29e68e1e974d8e4d39b7cfc24a40/modules/apps/collaboration/microblogs/microblogs-web/src/main/java/com/liferay/microblogs/web/internal/util/MicroblogsWebUtil.java#L216-L264
and implement it for the activities portlet.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by gregory-bretall** [comment]
@brianikim please comment ci test to run the tester

**Comment by brianikim** [comment]
@gregory-bretall , Sorry about that. I was finishing up my comment before running ci:test

**Comment by brianikim** [comment]
ci:test

**Comment by brianikim** [comment]
hey @gregory-bretall, I will re-implement my changes to make sure it fits source-format standards. Nothing popped up when I ran source format on my end, but I will double check and re-send you the PR. Thanks.

**Pull request closed without merging**
