### PR TITLE
LPP-32794 Logs are placed in an if block and does not enter if it is …

### PR DESCRIPTION
**Pull request by knchau**
…a ConnectException

### CODE REVIEW

**Comment by knchau** [comment]
https://issues.liferay.com/browse/LPP-32794

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Hi @knchau, just to let you know, all fixes we make to master have to be in the form of an LPS ticket. Once you've diagnosed that an LPP (customer driven ticket) is an issue in the product, you will create a related LPS ticket to that LPP. This is pretty easy now since we've just added a Create LPS button to all LPPs in the upper right corner of the ticket. Make sure to resend this linking the LPS in your commit summary on the PR (so when you're opening the PR, add the URL to the LPS) and also change the commit to include the LPS instead of the LPP. The reason we have to do it this way is because you are making a commit to Liferay CE which is public and LPPs, being for enterprise customers, are not a publicly available project unlike LPSs which anyone can create or access.

**Pull request closed without merging**
