### PR TITLE
LPS-78794 Enable Activities Portlet to Provide Profile Links for User…

### PR DESCRIPTION
**Pull request by brianikim**
… Mentions

### CODE REVIEW

**Comment by brianikim** [comment]
https://issues.liferay.com/browse/LPS-78794

Hello @gregory-bretall ,

The issue here is that the activities portlet and the microblogs portlet have conflicting behaviors in regards to how user mentions are displayed. For microblogs portlet, the user mention is converted into a href that allows users to click on the mentioned user's profile. For ex, in a microblogs portlet, if you write a comment saying "Hello @user" @user will be converted into the mentioned profile link. However, in the activities portlet, the same comment will be displayed as "Hello [@user]".

The fix here is to use the already available function of getProcessedContent found in
https://github.com/liferay/liferay-portal/blob/e0ffae30b9ea29e68e1e974d8e4d39b7cfc24a40/modules/apps/collaboration/microblogs/microblogs-web/src/main/java/com/liferay/microblogs/web/internal/util/MicroblogsWebUtil.java#L106-L112
which will ensure that @user is converted into the proper profile link.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci: test

**Comment by gregory-bretall** [comment]
ci:test

**Comment by gregory-bretall** [comment]
ci:retest

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1574

**Pull request closed without merging**
