### PR TITLE
LPS-79521

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-79521

Hello @gregory-bretall ,

The issue is that pagination in search for web content display is not working correctly when you search for content in a web content.
There are multiple layers for the reason that this issue is occuring.

When page.jsp (https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/search_paginator/page.jsp) is called to render the pagination bar at the bottom, it only renders the pagination bar if the searchContainer.getTotal() is greater than 0. In this case, getTotal() returns 0 because

https://github.com/liferay/liferay-portal/blob/5688f44cdc366f55240dbc0ce32f85b8675f656f/modules/apps/web-experience/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/display/context/AssetBrowserDisplayContext.java#L485

calls the method searchCount which ultimately leads to

https://github.com/liferay/liferay-portal/blob/f57516d0ede71a811898214b5cc1d5cd5bd8f04a/portal-impl/src/com/liferay/portlet/asset/service/impl/AssetEntryLocalServiceImpl.java#L594-L602

being called. Here, the method returns:
		
```
return searchCount(
			companyId, groupIds, userId, className, classTypeId, keywords,
keywords, keywords, null, null, showNonindexable, statuses, false);
```
Here, the keywords are passed as parameter three times, once each for Username, Title, and Description.
However, this implementation is incorrect because the Description column in Web Content Display returns the content if Description is empty. Thus, the search should also be doing a hit search for content as well.

Therefore, the fix is to add in a new method that takes in an extra parameter to account for the existence of content.

There are two commits here. The first one is to ensure that when the content is used as the summary, we should be extracting only the text from the web content and shorten the summary. The second commit implements the new method searchCount that accounts for the extra parameter.

If you have any questions, please let me know. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:retest

**Comment by gregory-bretall** [comment]
ci:stop

**Comment by gregory-bretall** [comment]
Reviewed and resent to https://github.com/jonathanmccann/liferay-portal/pull/1605

**Pull request closed without merging**
