### PR TITLE
[TS] LPS-82700 Browse icon isn't visible when using images to link

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @gregory-bretall,

please check my fix regarding browse icon on image.

https://issues.liferay.com/browse/LPP-30582
SMER: https://issues.liferay.com/browse/LPP-30566

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test

**Comment by gregory-bretall** [comment]
Sorry @rolandpakai, I didn't have time to test this change today and am out tomorrow. I will make sure to look at your fix on Monday though.

**Comment by jbalsas** [comment]
Hey @gregory-bretall, do you mind testing this asap and sending it to me? I'd like to send a final batch of editor changes to include in `7.1.x` with this one.

Thanks!

**Comment by gregory-bretall** [comment]
Hi @rolandpakai,
Your changes seem fine to me. I have resent the PR to https://github.com/jonathanmccann/liferay-portal/pull/1650/.

Please note next time to run source formatting before sending your pull.

Please also do not reference LPPs on PRs to a public Repo as the LPP project is not public. Instead, please link the related LPS ticket.

**Comment by rolandpakai** [comment]
Hi @gregory-bretall,

thanks you very much, i updated my PR comment.

Roland

**Pull request closed without merging**
