### PR TITLE
LPS-90645 Blog content out of range in the portlet

### PR DESCRIPTION
**Pull request by knchau**
The issue is when there is a paragraph with no space, the word does not break and so the content is able to roll off the portlet. I added `panel` css style to the blog content to break words, which prevents the content from going out of range in the portlet. 

https://issues.liferay.com/browse/LPS-90645

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
While this does seem to work, I think that adding panel might not be the right approach here. The only necessary CSS to fix the bug described here is word-wrap: break-word which, while including with the CSS associated with panel, comes along with several other styles in that case. I'd recommend just adding the one requisite style into blogs-web's CSS for the specific element you actually need to modifying (somewhere around https://github.com/liferay/liferay-portal/blob/1bbc5e152139131cd2d40b2d15d0f97f9fef5a7e/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/common_main.scss#L65) maybe just specify it's for p tags only as that's where we want to actually be putting the style.

Please let me know if you have any questions or need help implementing this. Please resend it to me when you've updated the fix.

**Pull request closed without merging**
