### PR TITLE
LPS-90506 Created a getYear() to check if there is a difference in ye…

### PR DESCRIPTION
**Pull request by knchau**
…ar between system's date and activity's date

### CODE REVIEW

**Comment by knchau** [comment]
https://issues.liferay.com/browse/LPS-90506

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
@knchau Please remember to run the source formatter on your local branch before sending in PRs in the future. Resent to https://github.com/jonathanmccann/liferay-portal/pull/1776

**Pull request closed without merging**
