### PR TITLE
LPS-90506 Created a getYear() to check if there is a difference in ye…

### PR DESCRIPTION
**Pull request by knchau**
…ar between system's date and activity's date

### CODE REVIEW

**Comment by knchau** [comment]
https://issues.liferay.com/browse/LPS-90506

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Hi @knchau,
I tested this and the change seems reasonable enough. My only recommendation would be to remove the conditional and just perform the check inside of where you currently are doing !diffYear since it will reduce the size of the fix. Let me know your thoughts on this suggestion and resend the pull request to me once you've made it.

**Comment by knchau** [comment]
Hi @gregory-bretall,
That's a great suggestion! I will make that change and resend the pull request.

**Pull request closed without merging**
