### PR TITLE
LPS-85564 Focus message board element for ios devices

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-85564

In message boards, when replying to a thread the screen does not focus on the reply editor when using an ios device. I found that focus() on ios works best when it is called on the element. This will scroll the page to the reply box and also open the keyboard. 

If there are any questions or comments, please let me know.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:reopen

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
@fortunatomaldonado, could you resend this PR with just 1 pull based on the changes I suggested to using the UA.ios property?

**Comment by fortunatomaldonado** [comment]
@gregory-bretall, do you mean one commit? If so, I'll do so now.

**Comment by gregory-bretall** [comment]
Sorry yes, I meant one commit. Thanks

**Comment by fortunatomaldonado** [comment]
@gregory-bretall, not a problem.
Resent pull https://github.com/gregory-bretall/liferay-portal/pull/107

**Pull request closed without merging**
