### PR TITLE
[TECHNICAL SUPPORT] LPS-85536 Unable to add images from DM in CKEditor

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @gregory-bretall ,

could you please review my fix? 

Thanks, Roland

LPS-85536

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Hi @rolandpakai,
The change makes sense to me, but wouldn't it be cleaner to just add the isSelectionEmpty function into CKEditor in a similar spot to where it is in AlloyEditor? That way we can leave the other code as is and have the function call not fail? It also might even allow us to remove the function call from AlloyEditor since it would (hopefully) fall back onto the CKEditor implementation of the function. But I'm definitely not 100% on that. Please let me know if you need any assistance in implementing the suggestion. Feel free to resend the PR to me when you've made the changes.

**Comment by rolandpakai** [comment]
Hi @gregory-bretall,

thanks for the review, but could you please help me where should i place the isSelectionEmpty function in CKEditor?

Thanks, Roland

**Comment by gregory-bretall** [comment]
I will try and look into it today and send you a pull @rolandpakai

**Comment by gregory-bretall** [comment]
Hi @rolandpakai you should I think be able to add it to a file in the _diffs folder in CKEditor. I recommend main.js (https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/main.js) but in my own limited testing I was unable to get the change to deploy. I will also be gone on PTO tomorrow so I won't be able to give further help on this until Monday unfortunately. I recommend pinging Daniel Sanz on the SME request if you absolutely need help on this before Monday.

**Pull request closed without merging**
