### PR TITLE
Pr 51e

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-91408

Tried various things to improve it but ultimately didn't come up with a refactor.

@ryannealeigh1

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
In testing this seemed mostly fine. Only issues were a bug that seemed to occur only on this branch's version of journal and not the most up to date as well as the commit message not being robust enough. @ryannealeigh1 just resend me the PR directly with 1 new commit combining the 2 here with a better commit message rebased onto a more recent version of Master.

**Comment by ryannealeigh** [comment]
Resubmitted https://github.com/gregory-bretall/liferay-portal/pull/176

**Comment by ryannealeigh1** [comment]
resubmitted https://github.com/gregory-bretall/liferay-portal/pull/176

**Pull request closed without merging**
