### PR TITLE
LPS-92877

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-92877

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
@holatuwol do we want to remove the calls to the reset function from other files since it no longer does anything? Otherwise this seems fine to me

**Comment by holatuwol** [comment]
@gregory-bretall : Sure, we should probably deprecate it and then remove the calls.

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
Thanks @holatuwol resent to https://github.com/jonathanmccann/liferay-portal/pull/1793

**Pull request closed without merging**
