### PR TITLE
LPS-91560 No tab - nav bar

### PR DESCRIPTION
**Pull request by knchau**
The issue was that the navigation bar was deemed unnecessary because it only contained one tab so I removed the navigation bar by removing the clay block that creates the navigation bar.

https://issues.liferay.com/browse/LPS-91560

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
https://github.com/adolfopa/liferay-portal/pull/872

**Comment by jonathanmccann** [comment]
ci:close

**Pull request closed without merging**
